### ISSUE TITLE
How to run CaloPointFlow

### ISSUE THREAD

**Issue by OswaldoBornemann** [simonschnake/CaloPointFlow#1]
How to run CaloPointFlow

**Comment by simonschnake** [comment]
Hello PPGGG
the scripts are in a very ruff shape. I plan to polish them in the near future.
I'm currently working on a different paper and therefore have no time at the moment.
The current version is probably hard to understand for someone else.

One could look at the original source code of PointFlow or the Discrete Point Flow for Inspiration.

Cheers
Simon
